### PR TITLE
Added quick-search in documentation.

### PR DESCRIPTION
**Pull request by praveenscience**
This fixes the issue #25. :+1:

### CODE REVIEW

**Comment by thesabbir** [comment]
Nice :smiley:

**Comment by praveenscience** [comment]
Thanks buddy. :+1:

**Comment by praveenscience** [comment]
I am just working on new stuff - Small / Medium / Large preview... :smiley:

**Comment by thesabbir** [comment]
Great !
You can also fix #40 
Cheers!

**Comment by praveenscience** [comment]
Thanks for your quick reply. Two commits have been pushed and created #42 ... :smile:

**Pull request merged**
